name: Docker Build and Push

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  # Update this with your GitHub username
  IMAGE_BASE: ghcr.io/${{ github.repository_owner }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    # This ensures we have permission to push to GHCR
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # Build and push Frontend
    - name: Build and push Frontend
      uses: docker/build-push-action@v5
      with:
        context: ./frontend
        file: ./frontend/Dockerfile
        push: true
        tags: |
          ${{ env.IMAGE_BASE }}/docx-converter-frontend:latest
          ${{ env.IMAGE_BASE }}/docx-converter-frontend:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    # Build and push Backend
    - name: Build and push Backend
      uses: docker/build-push-action@v5
      with:
        context: ./Backend
        file: ./Backend/Dockerfile
        push: true
        tags: |
          ${{ env.IMAGE_BASE }}/docx-converter-backend:latest
          ${{ env.IMAGE_BASE }}/docx-converter-backend:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
