name: Docker Build and Push
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  REGISTRY: ghcr.io
  # Make sure to use lowercase in the IMAGE_BASE
  IMAGE_BASE: ghcr.io/${{ github.repository_owner }}
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Convert owner to lowercase
      run: echo "OWNER_LC=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV
      
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build and push Frontend
      uses: docker/build-push-action@v5
      with:
        context: ./frontend
        file: ./frontend/Dockerfile
        push: true
        tags: |
          ghcr.io/${{ env.OWNER_LC }}/docx-converter-frontend:latest
          ghcr.io/${{ env.OWNER_LC }}/docx-converter-frontend:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
    
    - name: Build and push Backend
      uses: docker/build-push-action@v5
      with:
        context: ./Backend
        file: ./Backend/Dockerfile
        push: true
        tags: |
          ghcr.io/${{ env.OWNER_LC }}/docx-converter-backend:latest
          ghcr.io/${{ env.OWNER_LC }}/docx-converter-backend:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
